version: 2
jobs:
  run_tests:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm ci --verbose
      - run: make test-unit

  release:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm ci --verbose
      - run: npm publish

workflows:
  version: 2
  test_and_release:
    jobs:
      - run_tests
      - release:
          context:
            - npm-and-github
          requires:
            - run_tests
          filters:
            branches:
              only:
                - master
